core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('list.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

list/urls.py
from . import views
from django.urls import path

app_name = 'list'

urlpatterns = [
    path('', views.front_page, name='front_page'),
    path('home/', views.home, name='home'),
    path('delete/<list_id>/', views.delete, name='delete'),
    path('cross_off/<list_id>/', views.cross_off, name='cross_off'),
    path('uncross/<list_id>/', views.uncross, name='uncross'),
    path('edit/<list_id>/', views.edit, name='edit'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'member'

urlpatterns = [
    path('register_user/', views.register_user, name='register'),
    path('login_user/', views.login_user, name='login'),
    path('logout_user/', views.logout_user, name='logout'),
]

list/models.py
from django.db import models

# Create your models here.
class List(models.Model):
    item = models.CharField(max_length=255)
    completed = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.item + '|' + str(self.completed)

members/models.py
from dataclasses import field
from django.db import models

list/forms.py
from django import forms
from .models import List

class ListForm(forms.ModelForm):
    class Meta: 
        model = List
        fields = ['item', 'completed']

members/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

# Create your models here.
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

list/views.py
from django.shortcuts import render, redirect
from .models import List
from .forms import ListForm
from django.contrib import messages

# Create your views here.
def front_page(request):
 return render(request, 'index_base.html')

def home(request):
    if request.method == 'POST':
        form = ListForm(request.POST or None)

        if form.is_valid():
            form.save()
            all_items = List.objects.all
            messages.success(request, ('item has been added to list'))
            return render(request, 'home.html', {'all_items': all_items})

    else:
        all_items = List.objects.all
        return render(request, 'home.html', {'all_items': all_items})

def delete(request, list_id):
    item = List.objects.get(pk=list_id)
    item.delete()
    messages.success(request, ('item has been deleted from list'))
    return redirect('/')

def cross_off(request, list_id):
    item = List.objects.get(pk=list_id)
    item.completed = True
    item.save()
    return redirect('/')

def uncross(request, list_id):
    item = List.objects.get(pk=list_id)
    item.completed = False
    item.save()
    return redirect('/')

def edit(request, list_id):
    if request.method == 'POST':
        item = List.objects.get(pk=list_id)
        form = ListForm(request.POST or None, instance=item)

        if form.is_valid():
            form.save()
            messages.success(request, ('has been edited'))
            return redirect('/')
        else:
            item = List.objects.get(pk=list_id)
            return render(request, 'edit.html', {'item': item})

members/views.py
from email.mime import message
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages

# Create your views here.
def register_user(request):
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)

        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'cuenta a sido creado para "' + user + '"')
            return redirect('member:login')

    context = {'form': form}
    return render(request, 'authenticate/register.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'nombre de usuario o contraseña incorrecta')

    return render(request, 'authenticate/login.html')

def logout_user(request):
    logout(request)
    return redirect('member:login')

templates/authenticate/login.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
<style>
    .login-dark {
        height: 650px;
        background-size: cover;
        position: relative;
        padding: 6px;
        border-color: #03dac5;
    }

    .login-dark form {
        max-width: 450px;
        width: 90%;
        background-color: #1e2833;
        padding: 30px;
        border-radius: 4px;
        transform: translate(-50%, -50%);
        position: absolute;
        top: 50%;
        left: 50%;
        color: #fff;
        box-shadow: 3px 3px 4px #03dac5;
    }

    .login-dark .illustration {
        text-align: center;
        padding: 15px 0 20px;
        font-size: 100px;
        color: #2980ef;
    }

    .login-dark form .form-control {
        background: none;
        border: none;
        border-bottom: 1px solid #434a52;
        border-radius: 0;
        box-shadow: none;
        outline: none;
        color: inherit;
    }

    .login-dark form .btn-primary {
        background: #214a80;
        border: none;
        border-radius: 4px;
        padding: 11px;
        box-shadow: none;
        margin-top: 26px;
        text-shadow: none;
        outline: none;
    }

    .login-dark form .btn-primary:hover,
    .login-dark form .btn-primary:active {
        background: #214a80;
        outline: none;
    }

    .login-dark form .forgot {
        display: block;
        text-align: center;
        font-size: 12px;
        color: #6f7a85;
        opacity: 0.9;
        text-decoration: none;
    }

    .login-dark form .forgot:hover,
    .login-dark form .forgot:active {
        opacity: 1;
        text-decoration: none;
    }

    .login-dark form .btn-primary:active {
        transform: translateY(1px);
    }
</style>

<div class="login-dark">
    <form method="post">
        <h2 style="text-align: center;">Formulario de inicio de sesión</h2>
        <div class="illustration">
            <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-lock" viewBox="0 0 16 16">
                <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2zM5 8h6a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1z"/>
              </svg>
        </div>
        <div class="form-group"><input class="form-control" type="email" name="email" placeholder="Email"></div>
        <br>
        <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Contraseña"></div>
        <div style="text-align: center;">
            <button style="padding-left: 40%; padding-right: 40%;" class="btn btn-primary btn-block" type="submit">Log In</button>
        </div>
        <br>
        <a href="#" class="forgot">Restaurar Contraseña?</a>
    </form>
</div>


{% endblock %}

templates/authenticate/register.html
{% extends '../base.html' %}
{% load static %}

{% block content %}

<style>
    .login-dark {
        height: 650px;
        background-size: cover;
        position: relative;
        padding: 6px;
        border-color: #03dac5;
    }

    .login-dark form {
        max-width: 450px;
        width: 90%;
        background-color: #1e2833;
        padding: 30px;
        border-radius: 4px;
        transform: translate(-50%, -50%);
        position: absolute;
        top: 50%;
        left: 50%;
        color: #fff;
        box-shadow: 3px 3px 4px #03dac5;
    }

    .login-dark .illustration {
        text-align: center;
        padding: 15px 0 20px;
        font-size: 100px;
        color: #2980ef;
    }

    .login-dark form .form-control {
        background: none;
        border: none;
        border-bottom: 1px solid #434a52;
        border-radius: 0;
        box-shadow: none;
        outline: none;
        color: inherit;
    }

    .login-dark form .btn-primary {
        background: #214a80;
        border: none;
        border-radius: 4px;
        padding: 11px;
        box-shadow: none;
        margin-top: 26px;
        text-shadow: none;
        outline: none;
    }

    .login-dark form .btn-primary:hover,
    .login-dark form .btn-primary:active {
        background: #214a80;
        outline: none;
    }

    .login-dark form .forgot {
        display: block;
        text-align: center;
        font-size: 12px;
        color: #6f7a85;
        opacity: 0.9;
        text-decoration: none;
    }

    .login-dark form .forgot:hover,
    .login-dark form .forgot:active {
        opacity: 1;
        text-decoration: none;
    }

    .login-dark form .btn-primary:active {
        transform: translateY(1px);
    }
</style>

<div class="login-dark">
    <form method="POST">
        {% csrf_token %}
        <h2 style="text-align: center;">Formulario de inicio de sesión</h2>
        <div class="illustration">
            <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-lock" viewBox="0 0 16 16">
                <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2zM5 8h6a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1z"/>
              </svg>
        </div>
        <div class="form-group">{{ form.username }}</div>
        <br>
        <div class="form-group">{{ form.email }}</div>
        <br>
        <div class="form-group">{{ form.password1 }}</div>
        <br>
        <div class="form-group">{{ form.password2 }}</div>
        {{ form.errors }}
        <div style="text-align: center;">
            <input style="padding-left: 40%; padding-right: 40%;" type="submit" value="Log In" class="btn btn-primary btn-block">
            <!-- <button style="padding-left: 40%; padding-right: 40%;" class="btn btn-primary btn-block" type="submit">Log In</button> -->
        </div>
        <br>
        <a href="#" class="forgot">Restaurar Contraseña?</a>
    </form>
</div>

<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username..';
    form_fields[2].placeholder='Email..';
    form_fields[3].placeholder='Password..';
    form_fields[4].placeholder='Password..';

    for (var fields in form_fields){
        form_fields[fields].className += 'form-control'
    }
</script>

{% endblock %}

templates/edit.html
{% extends './base.html' %}
{% load static %}

{% block content %}

    {% if item %}
        <form action="" method="POST">
            {% csrf_token %}
            <input name="item" type='text' id='search' class="form-control search-form" placeholder="{{ item.item }}" value="{{ item.item }}">
            <input type="hidden" value="{{ item.completed }}" name="completed">
            <button type="submit">edit item</button>
        </form>
    {% endif %}

{% endblock %}

templates/home.html
{% extends './base.html' %}
{% load static %}

{% block content %}
<style>

.well {
  background-color: #03dac5;
}

.search-form {
  border-radius: 30px 0 0 30px;
}

.input-group {
  width:100%;
}

input-group-btn {
  max-width:38px;
}

#search {
  border: 1px;
}

.search-btn {
  cursor:pointer;
  border-radius: 0 30px 30px 0; 
  background-color:#fff;
  color:#669;
  
}

.text-center {
  color: #fff;
}

td {
    color: #f9f9f9;
}
.inir-cards {
  border: 2px solid red;
  border-radius: 6px;
  padding: 6px;
  border-color: #03dac5;

}

</style>

<h5 style="color: #c1cad2;">Bienvenido, {{ request.user }}</h5>

<div class="row">
    <div class="col">
        <div style="background: #181d27; border-color: #03dac5;" class="card">
            <div class="card-body">
                <body>
                    <div class="container">
                        <div id="content">
                            <form class='form-inline' method="POST">
                                {% csrf_token %}
                                <div class="input-group">
                                <input name="item" type='text' id='search' class="form-control search-form" placeholder="Agregar">
                                <span class="input-group-btn" style="width:39px">
                                    <button style="background: #03dac5;" id="search-this" type="submit" class="pull-right btn btn-default search-btn">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down" viewBox="0 0 16 16">
                                            <path style="color: #232323;" fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
                                        </svg>
                                    </button>
                                </span>
                                </div>
                            </form>
                        </div>
                    </div>
                </body>
                <br>


                {% if all_items %}
                    <table class="table">
                    {% for things in all_items %}

                        {% if things.completed %}
                            <tr style="background-color: #03dac5a4;">
                                <td style="text-decoration: line-through;">{{ things.item }}</td>
                                <td><center><a href="{% url 'list:edit' things.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                                      </svg>
                                </a></center></td>
                                <td><center><a href="{% url 'list:uncross' things.id %}">
                                    <svg style="color: rgb(0, 255, 0);" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-check-all" viewBox="0 0 16 16">
                                        <path d="M8.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L2.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093L8.95 4.992a.252.252 0 0 1 .02-.022zm-.92 5.14.92.92a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 1 0-1.091-1.028L9.477 9.417l-.485-.486-.943 1.179z"/>
                                      </svg>
                                </a></center></td>
                                <td><center><a href="{% url 'list:delete' things.id %}">
                                    <svg style="color: red;" xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                      </svg>
                                </a></center></td>
                            </tr>
                        {% else %}
                            <tr>
                                <td>{{ things.item }}</td>
                                <td><center><a href="{% url 'list:edit' things.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                                      </svg>
                                </a></center></td>
                                <td><center><a href="{% url 'list:cross_off' things.id %}">
                                    <svg style="color: rgb(3, 255, 3);" xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16">
                                        <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
                                      </svg>
                                </a></center></td>
                                <td><center><a href="{% url 'list:delete' things.id %}">
                                    <svg style="color: red;" xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                      </svg>
                                </a></center></td>
                            </tr>
                        {% endif %}
                        
                    {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col">
        <div style="background: #181d27; border-color: #03dac5;" class="card">
            <div class="card-body">
                <div class="container">
                    <div class="inir-cards">
                        {% if all_items %}
                            <div class="row">
                                {% for things in all_items %}

                                    {% if things.completed %}
                                        <div class="col-sm-8">
                                            <p style="text-decoration: line-through;">{{ things.item }}</p>
                                        </div>
                                        <div class="col">
                                            <center> <a href="{% url 'list:uncross' things.id %}">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2-all" viewBox="0 0 16 16">
                                                    <path d="M12.354 4.354a.5.5 0 0 0-.708-.708L5 10.293 1.854 7.146a.5.5 0 1 0-.708.708l3.5 3.5a.5.5 0 0 0 .708 0l7-7zm-4.208 7-.896-.897.707-.707.543.543 6.646-6.647a.5.5 0 0 1 .708.708l-7 7a.5.5 0 0 1-.708 0z"/>
                                                    <path d="m5.354 7.146.896.897-.707.707-.897-.896a.5.5 0 1 1 .708-.708z"/>
                                                </svg>
                                            </a></center>
                                        </div>
                                        <div class="col">
                                            <center><a href="{% url 'list:delete' things.id %}">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg>
                                            </a></center>
                                        </div>
                                    {% else %}
                                        <div class="col-sm-8">
                                            <p>{{ things.item }}</p>
                                        </div>
                                        <div class="col">
                                            <center><a href="{% url 'list:cross_off' things.id %}">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16">
                                                    <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
                                                  </svg>
                                            </a></center>
                                        </div>
                                        <div class="col">
                                            <center><a href="{% url 'list:delete' things.id %}">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                  </svg>
                                            </a></center>
                                        </div>
                                    {% endif %}

                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-body">
                This is some text within a card body.
            </div>
        </div>
    </div>
</div>
{% endblock %}